version: '3.8'

services:
  auth_vulnerabile_bypass:
    build:
      context: .
      dockerfile: Dockerfile.auth_vulnerable
    ports:
      - "5003:5000"
    container_name: security_auth_vulnerable

  auth_sicura_bypass:
    build:
      context: .
      dockerfile: Dockerfile.auth_secure
    ports:
      - "5004:5000"
    container_name: security_auth_secure